Sql 103 revamp tables
iflexhibit/iflexhibit-api pull request #105
Opened 2022-01-14 14:56 UTC by LyndonTomas

Closes #103 

Has successfully created the new tables in a database. 

Next TODO:
1.) Test new DB
2.) Add new ID conventions to System Overview.
3.) Send Screenshots

2022-01-15 05:52 UTC, LyndonTomas commented
**Update**
1.) Test new DB
- I am testing the new db locally, you can check the results [here](https://docs.google.com/spreadsheets/d/131UQQaVB-ViJBfjw7sQxI4rKLa_GGC5s/edit?usp=sharing&ouid=111635332390969582121&rtpof=true&sd=true).
- If you'd like me to test anything in the new local db, please fill out a new row in the testing sheet. You can also state what is the expected outcome.

2.) Add new ID conventions to System Overview.
- Kindly refer to the Google Sheet link above to see the new ID convention.

3.) Send Screenshots (Testing)
- https://drive.google.com/drive/folders/1uhmrMgxgkpocJR2_5JE74GpHdLC-fHB5?usp=sharing

2022-01-15 06:30 UTC, jp-ong requested changes
As mentioned in #103

>- **IMPORTANT**
>   - Check every syntaxes that may or may not be affected by these changes.
>   - For example,
>     - `CREATE TABLE users` syntax will be affected because of the `usertype_id`;
>     - `CREATE TABLE posts` syntax will be affected because of the `status_id`.
>     - `fetch_user_posts.sql` will be affected because of the `status_id`.
>   - Make sure to update the default values as well as the new data types in all the affected syntaxes.

Link to quoted text [here](https://github.com/iflexhibit/iflexhibit-api/issues/103#:~:text=on%20auto%2Dincrement.-,IMPORTANT,-Check%20every%20syntaxes)

Check on all PSQL files.
For example, you missed updating [src/repositories/sql/posts/fetch_all_guest.sql](https://github.com/iflexhibit/iflexhibit-api/blob/main/src/repositories/sql/posts/fetch_all_guest.sql)
Again, please be thorough with your task 😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭

2022-01-16 03:58 UTC, LyndonTomas commented
I've checked all of the files and even updated several concerns that were already solved during the past issues. On only have issues on 2 files
`fetch_all_guest.sql`
`fetch_user_post.sql`
Maybe it's just an error on my local server, but I will explain later in the meeting the error.

2022-01-16 09:13 UTC, jp-ong approved these changes

2022-01-16 09:13 UTC, merged